#!/usr/bin/env python3
"""
Theme generator — reads palette.toml and writes all target configs.

Usage:
    python3 generate.py           # generate all targets
    python3 generate.py ghostty   # generate specific target
    python3 generate.py zed

Adding a new tool: write a render_<toolname>(p, meta, out_dir) function
and register it in RENDERERS at the bottom.
"""

import json
import sys
import textwrap
import tomllib
from string import Template
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PALETTE_FILE = SCRIPT_DIR / "palette.toml"


# =============================================================================
# Helpers
# =============================================================================

def load_palette() -> tuple[dict, dict]:
    with open(PALETTE_FILE, "rb") as f:
        data = tomllib.load(f)

    if "meta" not in data or "colors" not in data:
        print(f"Invalid palette format in {PALETTE_FILE}.")
        print("Expected keys: [meta] and [colors] tables.")
        print("Example:")
        print('[meta]')
        print('name = "calm"')
        print('[colors]')
        sys.exit(1)

    return data["meta"], data["colors"]


def hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def strip_hex(h: str) -> str:
    """Return hex without leading #."""
    return h.lstrip("#")


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {path.relative_to(SCRIPT_DIR)}")


# =============================================================================
# Ghostty renderer
# The theme file is a subset of ghostty config — only color keys.
# Loaded before user config; user config overrides on conflict.
# Ref: https://ghostty.org/docs/features/theme
# =============================================================================

def render_ghostty(p: dict, meta: dict, out_dir: Path) -> None:
    name = meta["name"]

    # Ghostty ANSI palette indices 0-15:
    # 0  black (normal)    8  bright black
    # 1  red               9  bright red
    # 2  green            10  bright green
    # 3  yellow           11  bright yellow
    # 4  blue             12  bright blue
    # 5  magenta          13  bright magenta
    # 6  cyan             14  bright cyan
    # 7  white            15  bright white
    lines = [
        f"# Calm — generated by themes/generate.py",
        f"# Edit palette.toml, not this file.",
        f"",
        f"background = {strip_hex(p['bg1'])}",
        f"foreground = {strip_hex(p['fg0'])}",
        f"",
        f"cursor-color = {strip_hex(p['accent'])}",
        f"selection-background = {strip_hex(p['bg3'])}",
        f"selection-foreground = {strip_hex(p['fg0'])}",
        f"",
        f"# Normal (0-7)",
        f"palette = 0={p['bg3']}",     # black  → dark surface (visible on bg)
        f"palette = 1={p['red']}",
        f"palette = 2={p['green']}",
        f"palette = 3={p['yellow']}",
        f"palette = 4={p['blue']}",
        f"palette = 5={p['magenta']}",
        f"palette = 6={p['cyan']}",
        f"palette = 7={p['fg1']}",     # white  → muted fg
        f"",
        f"# Bright (8-15)",
        f"palette = 8={p['bg4']}",     # bright black → slightly lighter surface
        f"palette = 9={p['red']}",
        f"palette = 10={p['green']}",
        f"palette = 11={p['yellow']}",
        f"palette = 12={p['accent']}",
        f"palette = 13={p['magenta']}",
        f"palette = 14={p['cyan']}",
        f"palette = 15={p['fg0']}",    # bright white → primary fg
    ]

    write(out_dir / "ghostty" / f"{name}.theme", "\n".join(lines) + "\n")


# =============================================================================
# Zed renderer
# Schema: https://zed.dev/schema/themes/v0.2.0.json
# Ref:    https://zed.dev/docs/themes
# =============================================================================

def render_zed(p: dict, meta: dict, out_dir: Path) -> None:
    name = meta["name"].capitalize()

    theme = {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": name,
        "author": "",
        "themes": [
            {
                "name": f"{name} Dark",
                "appearance": "dark",
                "style": {
                    # ── Backgrounds ──────────────────────────────────────────
                    "background":               p["bg1"],
                    "editor.background":        p["bg1"],
                    "panel.background":         p["bg2"],
                    "terminal.background":      p["bg1"],

                    # Active/elevated surfaces
                    "editor.active_line.background":      p["bg2"],
                    "editor.highlighted_line.background": p["bg3"],
                    "element.hover":                      p["bg3"],
                    "element.selected":                   p["bg3"],
                    "element.active":                     p["bg4"],

                    # Tab bar
                    "tab_bar.background":           p["bg0"],
                    "tab.active_background":        p["bg1"],
                    "tab.inactive_background":      p["bg0"],

                    # ── Borders ───────────────────────────────────────────────
                    "border":           p["bg4"],
                    "border.variant":   p["bg3"],
                    "border.focused":   p["accent"],
                    "border.selected":  p["accent"],
                    "border.disabled":  p["bg3"],

                    # ── Text ──────────────────────────────────────────────────
                    "text":           p["fg0"],
                    "text.muted":     p["fg1"],
                    "text.disabled":  p["fg2"],
                    "text.accent":    p["accent"],

                    # ── Editor chrome ─────────────────────────────────────────
                    "editor.foreground":          p["fg0"],
                    "editor.gutter.background":   p["bg1"],
                    "editor.line_number":         p["fg2"],
                    "editor.active_line_number":  p["fg1"],

                    # Selection
                    "editor.selection.background": p["bg3"],

                    # Find/search highlight
                    "search.match_background": p["bg4"],

                    # ── Diff / git ────────────────────────────────────────────
                    "created":          p["green"],
                    "modified":         p["yellow"],
                    "deleted":          p["red"],
                    "conflict":         p["orange"],
                    "hidden":           p["fg2"],
                    "renamed":          p["cyan"],

                    # ── Terminal ──────────────────────────────────────────────
                    "terminal.foreground":      p["fg0"],
                    "terminal.ansi.black":      p["bg3"],
                    "terminal.ansi.red":        p["red"],
                    "terminal.ansi.green":      p["green"],
                    "terminal.ansi.yellow":     p["yellow"],
                    "terminal.ansi.blue":       p["blue"],
                    "terminal.ansi.magenta":    p["magenta"],
                    "terminal.ansi.cyan":       p["cyan"],
                    "terminal.ansi.white":      p["fg1"],
                    "terminal.ansi.bright_black":   p["bg4"],
                    "terminal.ansi.bright_red":     p["red"],
                    "terminal.ansi.bright_green":   p["green"],
                    "terminal.ansi.bright_yellow":  p["yellow"],
                    "terminal.ansi.bright_blue":    p["accent"],
                    "terminal.ansi.bright_magenta": p["magenta"],
                    "terminal.ansi.bright_cyan":    p["cyan"],
                    "terminal.ansi.bright_white":   p["fg0"],

                    # ── Status / semantic ─────────────────────────────────────
                    "error":     p["red"],
                    "warning":   p["yellow"],
                    "info":      p["blue"],
                    "hint":      p["fg2"],
                    "success":   p["green"],

                    # ── Scrollbar ─────────────────────────────────────────────
                    "scrollbar.thumb.background":       p["bg4"],
                    "scrollbar.thumb.hover_background": p["fg2"],
                    "scrollbar.track.background":       p["bg1"],
                    "scrollbar.track.border":           p["bg2"],

                    # ── Syntax ────────────────────────────────────────────────
                    "syntax": {
                        "attribute":    {"color": p["yellow"]},
                        "boolean":      {"color": p["orange"]},
                        "comment":      {"color": p["fg2"], "font_style": "italic"},
                        "comment.doc":  {"color": p["fg1"], "font_style": "italic"},
                        "constant":     {"color": p["orange"]},
                        "constructor":  {"color": p["cyan"]},
                        "embedded":     {"color": p["fg0"]},
                        "emphasis":     {"color": p["fg0"], "font_style": "italic"},
                        "emphasis.strong": {"color": p["fg0"], "font_weight": 700},
                        "enum":         {"color": p["cyan"]},
                        "function":     {"color": p["blue"]},
                        "function.method": {"color": p["blue"]},
                        "hint":         {"color": p["fg2"]},
                        "keyword":      {"color": p["magenta"]},
                        "label":        {"color": p["yellow"]},
                        "link_text":    {"color": p["accent"]},
                        "link_uri":     {"color": p["accent"]},
                        "number":       {"color": p["orange"]},
                        "operator":     {"color": p["fg1"]},
                        "predictive":   {"color": p["fg2"], "font_style": "italic"},
                        "preproc":      {"color": p["magenta"]},
                        "primary":      {"color": p["fg0"]},
                        "property":     {"color": p["cyan"]},
                        "punctuation":  {"color": p["fg2"]},
                        "punctuation.bracket":    {"color": p["fg2"]},
                        "punctuation.delimiter":  {"color": p["fg2"]},
                        "punctuation.list_marker":{"color": p["fg1"]},
                        "punctuation.special":    {"color": p["yellow"]},
                        "string":       {"color": p["green"]},
                        "string.escape":{"color": p["yellow"]},
                        "string.regex": {"color": p["cyan"]},
                        "string.special":{"color": p["yellow"]},
                        "tag":          {"color": p["red"]},
                        "text.literal": {"color": p["green"]},
                        "title":        {"color": p["fg0"], "font_weight": 700},
                        "type":         {"color": p["cyan"]},
                        "type.builtin": {"color": p["cyan"]},
                        "variable":     {"color": p["fg0"]},
                        "variable.special": {"color": p["orange"]},
                        "variant":      {"color": p["cyan"]},
                    },
                },
            }
        ],
    }

    write(
        out_dir / "zed" / f"{meta['name']}.json",
        json.dumps(theme, indent=2) + "\n",
    )


# =============================================================================
# Obsidian renderer
# Obsidian uses CSS custom properties for theming.
# =============================================================================

def render_obsidian(p: dict, meta: dict, out_dir: Path) -> None:
    css = Template(
        textwrap.dedent("""
        :root,
        .theme-dark,
        .theme-light {
          --background-primary:       $bg1;
          --background-primary-alt:   $bg2;
          --background-secondary:     $bg2;
          --background-secondary-alt: $bg0;
          --background-modifier-hover:   $bg3;
          --background-modifier-active:  $bg3;
          --background-modifier-border:  $bg4;

          --text-normal:    $fg0;
          --text-muted:     $fg1;
          --text-faint:     $fg2;
          --text-accent:    $accent;
          --text-accent-hover: $accent;
          --text-on-accent: $bg1;

          --interactive-accent:       $accent;
          --interactive-accent-hover: $accent;

          --titlebar-background: $bg0;
          --status-bar-background: $bg0;
          --ribbon-background: $bg0;
          --modal-background: $bg2;

          --color-red:     $red;
          --color-orange:  $orange;
          --color-yellow:  $yellow;
          --color-green:   $green;
          --color-cyan:    $cyan;
          --color-blue:    $blue;
          --color-purple:  $magenta;
        }

        .cm-editor,
        .cm-s-obsidian {
          --code-background: $bg0;
        }

        .cm-editor .cm-keyword,
        .cm-s-obsidian .cm-keyword { color: $magenta; }
        .cm-editor .cm-def,
        .cm-s-obsidian .cm-def { color: $blue; }
        .cm-editor .cm-variable,
        .cm-s-obsidian .cm-variable { color: $fg0; }
        .cm-editor .cm-property,
        .cm-s-obsidian .cm-property { color: $cyan; }
        .cm-editor .cm-string,
        .cm-s-obsidian .cm-string { color: $green; }
        .cm-editor .cm-number,
        .cm-s-obsidian .cm-number { color: $orange; }
        .cm-editor .cm-comment,
        .cm-s-obsidian .cm-comment { color: $fg2; font-style: italic; }
        .cm-editor .cm-operator,
        .cm-s-obsidian .cm-operator { color: $fg1; }
        .cm-editor .cm-type,
        .cm-s-obsidian .cm-type { color: $cyan; }
        """
        )
    )
    write(
        out_dir / "obsidian" / "calm.css",
        css.substitute(**p).lstrip(),
    )


# =============================================================================
# Registry — add new tools here
# =============================================================================

RENDERERS: dict[str, callable] = {
    "ghostty": render_ghostty,
    "zed":     render_zed,
    "obsidian": render_obsidian,
    # "btop":   render_btop,
    # "delta":  render_delta,
    # "bat":    render_bat,
    # "starship": render_starship,
}


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    meta, colors = load_palette()
    out_dir = SCRIPT_DIR

    requested = sys.argv[1:] or list(RENDERERS)
    unknown = set(requested) - set(RENDERERS)
    if unknown:
        print(f"Unknown target(s): {', '.join(sorted(unknown))}")
        print(f"Available: {', '.join(sorted(RENDERERS))}")
        sys.exit(1)

    print(f"Generating palette '{meta['name']}' ({meta['variant']})...")
    for target in requested:
        RENDERERS[target](colors, meta, out_dir)
    print("Done.")


if __name__ == "__main__":
    main()
